config/routes.rb
Rails.application.routes.draw do
  resources :kittens
  root "kittens#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html # renders the HTML view
      format.json { render json: @kittens } # renders JSON
    end
  end

  def show
    @kitten = Kitten.find(params[:id])
    respond_to do |format|
      format.html # renders the HTML view
      format.json { render json: @kitten } 
    end  
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      redirect_to @kitten, notice: 'Kitten was successfully created.'
    else
      render :new
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])
    if @kitten.update(kitten_params)
      redirect_to @kitten, notice: 'Kitten was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy
    redirect_to kittens_url, notice: 'Kitten was successfully destroyed.'
  end
  

  private

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/edit.html.erb
<h1 class="mb-4 text-2xl font-extrabold leading-none tracking-tight text-gray-900 dark:text-white">Update Kitten</h1>

<%= form_with model: @kitten do |form| %>
  <div class="mb-5">
    <%= form.label :name, class:"block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
    <%= form.text_field :name, class:"bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>
  <div class="mb-5">
    <%= form.label :age, class:"block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
    <%= form.number_field :age, class:"bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"    %>
  </div>
  <div class="mb-5">
    <%= form.label :cuteness, class:"block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
    <%= form.number_field :cuteness, class:"bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>
  <div class="mb-5">
    <%= form.label :softness, class:"block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
    <%= form.number_field :softness, class:"bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>
  <%= form.submit class: "text-right text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800" %>
<% end %>

app/views/kittens/index.html.erb
<h1 class="mb-4 text-2xl font-extrabold leading-none tracking-tight text-gray-900 dark:text-white">Kittens List</h1>
<div class="flex justify-end">
  <%= link_to "Create a new kitten", new_kitten_path, class: "text-right text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800" %>
</div>
<div class="container w-full mx-auto">
  <table class="w-full table-auto text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
    <thead class"text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
      <tr>
        <th>Name</th>
        <th>Age</th>
        <th>Cuteness</th>
        <th>Softness</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @kittens.each do |kitten| %>
        <tr>
          <td><%= kitten.name %></td>
          <td><%= kitten.age %></td>
          <td><%= kitten.cuteness %></td>
          <td><%= kitten.softness %></td>
          <td>
            <%= link_to "Show", kitten_path(kitten) %> |
            <%= link_to "Edit", edit_kitten_path(kitten) %> |
            <%= button_to "Delete", kitten_path(kitten), method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>  

app/views/kittens/new.html.erb
<h1 class="mb-4 text-2xl font-extrabold leading-none tracking-tight text-gray-900 dark:text-white">Create a new Kitten</h1>

<%= form_with model: @kitten do |form| %>
  <div class="mb-5">
    <%= form.label :name, class:"block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
    <%= form.text_field :name, class:"bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>
  <div class="mb-5">
    <%= form.label :age, class:"block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
    <%= form.number_field :age, class:"bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"    %>
  </div>
  <div class="mb-5">
    <%= form.label :cuteness, class:"block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
    <%= form.number_field :cuteness, class:"bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>
  <div class="mb-5">
    <%= form.label :softness, class:"block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
    <%= form.number_field :softness, class:"bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>
  <%= form.submit class: "text-right text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800" %>
<% end %>

app/views/kittens/show.html.erb
<h1><%= @kitten.name %></h1>
<p><%= @kitten.age %></p>
<p><%= @kitten.cuteness %></p>
<p><%= @kitten.softness %></p>

<%= link_to "Back", kittens_path %>
<%= link_to "Edit", edit_kitten_path(@kitten) %>
<%= button_to "Delete", kitten_path(@kitten), method: :delete, data: { confirm: 'Are you sure?', turbo: false } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.tailwindcss.com"></script>

  </head>

  <body>
    <div class="container mx-auto max-w-4xl p-4">
      <% if notice.present? %>
        <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>